/* Example SQL file for creating a database of music */

CREATE SEQUENCE artists_sequence;
CREATE TABLE artists (
  id integer PRIMARY KEY DEFAULT nextval('artists_sequence'),
  name varchar(256) NOT NULL
);

CREATE SEQUENCE albums_sequence;
CREATE TABLE albums (
  id integer PRIMARY KEY DEFAULT nextval('albums_sequence'),
  artist_id integer NOT NULL,
  name varchar(256) NOT NULL
);

CREATE SEQUENCE songs_sequence;
CREATE TABLE songs (
  id integer PRIMARY KEY DEFAULT nextval('songs_sequence'),
  album_id integer NOT NULL,
  title varchar(256) NOT NULL,
  year integer,
  track_number integer
);

/* Auto-generated from scripts/music-sql.rb */
INSERT INTO artists (name) VALUES ('Depeche Mode');
INSERT INTO albums (artist_id, name) SELECT id, 'Black Celebration' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'World Full Of Nothing', 1986, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sometimes', 1986, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Question Of Lust', 1986, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Fly On The Windscreen - Final', 1986, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'But Not Tonight', 1986, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Stripped', 1986, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'New Dress', 1986, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Question Of Time', 1986, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Dressed In Black', 1986, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Black Celebration', 1986, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Here Is The House', 1986, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'It Doesn''t Matter Two', 1986, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Black Celebration';
INSERT INTO albums (artist_id, name) SELECT id, 'Music For The Masses' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'It''s Called a Heart - EP' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Playing The Angel' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Damaged People', 2005, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Suffer Well', 2005, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Nothing''s Impossible', 2005, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'I Want It All', 2005, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Pain That I''m Used To', 2005, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Introspectre', 2005, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'John The Revelator', 2005, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Precious', 2005, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Lilian', 2005, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Darkest Star', 2005, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Sinner In Me', 2005, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Macro', 2005, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Playing The Angel';
INSERT INTO albums (artist_id, name) SELECT id, 'Songs Of Faith And Devotion' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Speak & Spell' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'What''s Your Name?', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Just Can''t Get Enough - Schizo', 2006, 16 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Shout', 2006, 14 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Puppets', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Dreaming Of Me', 2006, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Photographic', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Any Second Now', 2006, 15 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'New Life', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Boys Say Go!', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Nodisco!', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Just Can''t Get Enough', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Ice Machine', 2006, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Any Second Now', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Big Muff', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Tora! Tora! Tora!', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'I Sometime Wish I Was Dead', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Speak & Spell';
INSERT INTO albums (artist_id, name) SELECT id, 'Sounds Of The Universe' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Perfect', 2009, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Hole To Feed', 2009, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Spacewalker', 2009, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Corrupt', 2009, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'In Chains', 2009, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Wrong', 2009, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Little Soul', 2009, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Come Back', 2009, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Jezebel', 2009, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Peace', 2009, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'In Sympathy', 2009, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Fragile Tension', 2009, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Miles Away / The Truth Is', 2009, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Sounds Of The Universe';
INSERT INTO albums (artist_id, name) SELECT id, 'Photographic - Single' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'A Broken Frame' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'My Secret Garden', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Sun And The Rainfall', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Monument', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Photograph Of You', 2006, 16 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Leave In Silence', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Nothing To Fear', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'See You', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'My Secret Garden', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'See You', 2006, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Meaning Of Love', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Nothing To Fear', 2006, 14 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Meaning Of Love', 2006, 15 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Satellite', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Excerpt From: My Secret Garden', 2006, 19 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Photograph Of You', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Now This Is Fun', 2006, 17 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Oberkorn', 2006, 18 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Shouldn''t Have Done That', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Satellite', 2006, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'A Broken Frame';
INSERT INTO albums (artist_id, name) SELECT id, 'Shake the Disease - EP' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Martyr - Single' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Construction Time Again' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Everything Counts', 1987, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Love, In Itself', 1987, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'More Than A Party', 1987, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Shame', 1987, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Pipeline', 1987, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Landscape Is Changing', 1987, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Told You So', 1987, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'And Then...', 1987, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Two Minute Warning', 1987, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Everything Counts', 1987, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Construction Time Again';
INSERT INTO albums (artist_id, name) SELECT id, 'Precious' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, '101' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Ultra' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Useless', 2007, 15 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Insight', 2007, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sister Of Night', 2007, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'It''s No Good', 2007, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Headstar', 2007, 20 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Barrel Of A Gun', 2007, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Useless', 2007, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Only When I Lose Myself', 2007, 18 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Slowblow', 2007, 17 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Junior Painkiller', 2007, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Painkiller', 2007, 16 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Home', 2007, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Uselink', 2007, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Surrender', 2007, 19 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Jazz Thieves', 2007, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'It''s No Good', 2007, 14 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Barrel Of A Gun', 2007, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Love Thieves', 2007, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Bottom Line', 2007, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Freestate', 2007, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Ultra';
INSERT INTO albums (artist_id, name) SELECT id, 'Only When I Lose Myself - EP' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'A Pain That I''m Used To - EP' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'People Are People - EP' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'World In My Eyes - EP' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Some Great Reward' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'It Doesn''t Matter', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Somebody', 2006, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Blasphemous Rumours', 2006, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Lie To Me', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Somebody', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Blasphemous Rumours', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Master And Servant', 2006, 14 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'If You Want', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'People Are People', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Stories Of Old', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'People Are People', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'In Your Memory', 2006, 15 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Master And Servant', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, '', 2006, 16 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'If You Want', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Something To Do', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Somebody', 2006, 17 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Some Great Reward';
INSERT INTO albums (artist_id, name) SELECT id, 'Violator' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sibeling', 2006, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Halo', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Personal Jesus', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sea Of Sin', 2006, 15 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Kaleid', 2006, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sweetest Perfection', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Waiting For The Night', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Memphisto', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Enjoy The Silence', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Policy Of Truth', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Blue Dress', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'World In My Eyes', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Dangerous', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Happiest Girl', 2006, 14 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Clean', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Depeche Mode' AND albums.name = 'Violator';
INSERT INTO albums (artist_id, name) SELECT id, 'People Are People' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Exciter' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'A Question of Time' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO albums (artist_id, name) SELECT id, 'Everything Counts' FROM artists WHERE name = 'Depeche Mode';
INSERT INTO artists (name) VALUES ('The Knife');
INSERT INTO albums (artist_id, name) SELECT id, 'Hannah Med H Soundtrack' FROM artists WHERE name = 'The Knife';
INSERT INTO albums (artist_id, name) SELECT id, 'We Share Our Mothers'' Health' FROM artists WHERE name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'We Share Our Mothers'' Health', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'We Share Our Mothers'' Health';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'We Share Our Mothers'' Health', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'We Share Our Mothers'' Health';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'We Share Our Mothers'' Health', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'We Share Our Mothers'' Health';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'We Share Our Mothers'' Health', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'We Share Our Mothers'' Health';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'We Share Our Mothers'' Health', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'We Share Our Mothers'' Health';
INSERT INTO albums (artist_id, name) SELECT id, 'Silent Shout' FROM artists WHERE name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Na Na Na', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Forest Families', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Captain', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Neverland', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Silent Shout', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Marble House', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Still Light', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'One Hit', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'We Share Our Mothers'' Health', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'From Off To On', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Like A Pen', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Silent Shout';
INSERT INTO albums (artist_id, name) SELECT id, 'Deep Cuts' FROM artists WHERE name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Listen Now', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Got 2 Let U', 2006, 12 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Rock Classics', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Cop', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'She''s Having A Baby', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Bridge', 2006, 17 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Pass This On', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Pass This On', 2006, 18 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'This Is Now', 2006, 15 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'You Take My Breath Away', 2006, 20 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'You Make Me Like Charity', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Girls'' Night Out', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Heartbeats', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Is It Medicine', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Handy-Man', 2006, 16 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Heartbeats', 2006, 19 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'One For You', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'You Take My Breath Away', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Hangin'' Out', 2006, 14 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Behind The Bushes', 2006, 13 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'Deep Cuts';
INSERT INTO albums (artist_id, name) SELECT id, 'The Knife' FROM artists WHERE name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Zapata', 2006, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Bird', 2006, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Parade', 2006, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Lung', 2006, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'N.Y Hotel', 2006, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'I Just Had To Die', 2006, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Kino', 2006, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Reindeer', 2006, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Neon', 2006, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Lasagna', 2006, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'I Take Time', 2006, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'The Knife' AND albums.name = 'The Knife';
INSERT INTO artists (name) VALUES ('The Beatles');
INSERT INTO albums (artist_id, name) SELECT id, 'Sgt. Pepper''s Lonely Hearts Club Band' FROM artists WHERE name = 'The Beatles';
INSERT INTO albums (artist_id, name) SELECT id, 'Abbey Road' FROM artists WHERE name = 'The Beatles';
INSERT INTO albums (artist_id, name) SELECT id, 'A Hard Day''s Night' FROM artists WHERE name = 'The Beatles';
INSERT INTO artists (name) VALUES ('Death Cab for Cutie');
INSERT INTO albums (artist_id, name) SELECT id, 'We Have The Facts And We''re Voting Yes' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'Something About Airplanes (Deluxe Edition)' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Line Of Best Fit', 2008, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Amputations', 2008, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Something About ''Something Abo', 2008, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'State Street Residential', 2008, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Amputations', 2008, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Fake Frowns', 2008, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Your Bruise', 2008, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Your Bruise', 2008, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'President Of What?', 2008, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Champagne From A Paper Cup', 2008, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Pictures In An Exhibition', 2008, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'President Of What?', 2008, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sleep Spent', 2008, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sweet and Tender Hooligan', 2008, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Pictures In An Exhibition', 2008, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Fake Frowns', 2008, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Bend To Squares', 2008, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Face That Launched 1000 Sh', 2008, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Something About Airplanes (Deluxe Edition)';
INSERT INTO albums (artist_id, name) SELECT id, 'The Photo Album' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'Transatlanticism' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'You Can Play These Songs With Chords' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'The Stability EP' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'Forbidden Love (EP)' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'The Open Door' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Litttle Bribes', 2009, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'The Open Door';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'My Mirror Speaks', 2009, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'The Open Door';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'A Diamond And A Tether', 2009, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'The Open Door';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'I Was Once A Loyal Lover', 2009, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'The Open Door';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Talking Bird', 2009, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'The Open Door';
INSERT INTO albums (artist_id, name) SELECT id, 'Plans' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'Narrow Stairs' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'Crooked Teeth - EP' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO albums (artist_id, name) SELECT id, 'Codes and Keys' FROM artists WHERE name = 'Death Cab for Cutie';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Codes And Keys', 2011, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Home Is A Fire', 2011, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Portable Television', 2011, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Monday Morning', 2011, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Doors Unlocked And Open', 2011, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Unobstructed Views', 2011, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Stay Young, Go Dancing', 2011, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Underneath The Sycamore', 2011, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'You Are A Tourist', 2011, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Some Boys', 2011, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'St. Peter''s Cathedral', 2011, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Death Cab for Cutie' AND albums.name = 'Codes and Keys';
INSERT INTO artists (name) VALUES ('Zero 7');
INSERT INTO albums (artist_id, name) SELECT id, 'Simple Things' FROM artists WHERE name = 'Zero 7';
INSERT INTO albums (artist_id, name) SELECT id, 'Yeah Ghost' FROM artists WHERE name = 'Zero 7';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Swing', 2009, 3 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Solastalgia', 2009, 9 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Pop Art Blue', 2009, 5 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Count Me Out', 2009, 1 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Ghost sYMbOL', 2009, 7 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Medicine Man', 2009, 6 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Everything Up', 2009, 4 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Sleeper', 2009, 8 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'The Road', 2009, 10 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'Mr McGee', 2009, 2 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO songs (album_id, title, year, track_number) SELECT albums.id, 'All Of Us', 2009, 11 FROM artists, albums WHERE artists.id = albums.artist_id AND artists.name = 'Zero 7' AND albums.name = 'Yeah Ghost';
INSERT INTO albums (artist_id, name) SELECT id, 'The Garden' FROM artists WHERE name = 'Zero 7';
